# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
#
# pyuic5 name.ui -o name.py - запускаем из папки с файлом ui в cmd


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(300, 400))
        MainWindow.setBaseSize(QtCore.QSize(300, 400))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setMinimumSize(QtCore.QSize(300, 400))
        self.centralWidget.setMaximumSize(QtCore.QSize(300, 400))
        self.centralWidget.setBaseSize(QtCore.QSize(300, 400))
        self.centralWidget.setObjectName("centralWidget")
        self.text_input = QtWidgets.QLineEdit(self.centralWidget)
        self.text_input.setGeometry(QtCore.QRect(225, 50, 50, 20))
        self.text_input.setMinimumSize(QtCore.QSize(30, 20))
        self.text_input.setMaximumSize(QtCore.QSize(70, 20))
        self.text_input.setMaxLength(5)
        self.text_input.setValidator(QtGui.QIntValidator(0, 99999))
        self.text_input.setObjectName("text_input")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(15, 15, 120, 20))
        self.label_2.setMinimumSize(QtCore.QSize(100, 20))
        self.label_2.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.open_direct = QtWidgets.QPushButton(self.centralWidget)
        self.open_direct.setGeometry(QtCore.QRect(225, 15, 40, 20))
        self.open_direct.setMinimumSize(QtCore.QSize(40, 20))
        self.open_direct.setMaximumSize(QtCore.QSize(40, 30))
        self.open_direct.setObjectName("open_direct")
        self.btn_exit = QtWidgets.QPushButton(self.centralWidget)
        self.btn_exit.setGeometry(QtCore.QRect(170, 320, 111, 70))
        self.btn_exit.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_exit.setMaximumSize(QtCore.QSize(150, 70))
        self.btn_exit.setBaseSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.btn_exit)
        self.btn_start = QtWidgets.QPushButton(self.centralWidget)
        self.btn_start.setGeometry(QtCore.QRect(10, 320, 111, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_start.setMaximumSize(QtCore.QSize(150, 70))
        self.btn_start.setBaseSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setTabletTracking(False)
        self.btn_start.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_start.setObjectName("btn_start")
        self.buttonGroup.addButton(self.btn_start)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(15, 50, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 20))
        self.label.setMaximumSize(QtCore.QSize(100, 20))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.info = QtWidgets.QLabel(self.centralWidget)
        self.info.setGeometry(QtCore.QRect(15, 201, 16, 16))
        self.info.setText("")
        self.info.setObjectName("info")
        self.log_out = QtWidgets.QTextEdit(self.centralWidget)
        self.log_out.setGeometry(QtCore.QRect(10, 85, 271, 171))
        self.log_out.setReadOnly(True)
        self.log_out.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.log_out.setFont(font)
        self.log_out.setObjectName("log_out")
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 270, 270, 30))
        self.progressBar.setMinimumSize(QtCore.QSize(250, 30))
        self.progressBar.setMaximumSize(QtCore.QSize(270, 30))
        self.progressBar.setBaseSize(QtCore.QSize(270, 30))
        self.progressBar.setAcceptDrops(False)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "myzuca.club"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Папка назначения:</span></p></body></html>"))
        self.open_direct.setText(_translate("MainWindow", "..."))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Скачать треки</span></p></body></html>"))

